#!/bin/sh

#install cross compile essential
echo "\e[34m"
echo "Installing cross-build dependencies..."
echo "\e[0m"

apt-get -y install gfortran\

#install opencv dev libs
echo "\e[34m"
echo "Installing cv codec libs..."
echo "\e[0m"

apt -y install  build-essential cmake git pkg-config libgtk-3-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev python3-dev python3-numpy \
    libtbb2 libtbb-dev libdc1394-22-dev
